# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f24a9ccaaf12c91aa402249c31c431f2345d0a1e4beb248c197dc9c4864a345ce2f2e1a236a800ade294ee1677ca3d6f7cb484c1c2432c45acc55b898fa78c03

test:
  secret_key_base: 0cbaefd1e15300247b5ec1cc03e8ae81e141ce9a0c53f83ae978d61e94b4956726c83cce5a88c5f16e4d7b3e0387a855d18bec7e37c1b11d500db1882b106dab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
